services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client-vue
    depends_on:
      - backend
    expose:
      - '80'
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge