services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=api.smart-ris.ru
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=redirect
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client-vue
    depends_on:
      - backend
    expose:
      - '80'
    restart: always
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=smart-ris.ru
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=redirect

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=smart-ris.ru
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./conf.d:/etc/nginx/conf.d

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: smart-ris@info.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge